apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-ec2-nodeclass
spec:
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: "eksNodeInstanceRole"
  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/ecommerce-qual: shared
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/ecommerce-qual: owned
  tags:
    app.kubernetes.io/created-by: karpenter
    cluster: <cluster-name>
    Name: eks-karpenter-node